### PR TITLE
🌱 pr-verify: use env var for passing the PR title

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
Thanks!
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
Thanks!

/approve

**Pull request merged**
