### PR TITLE
:seedling: Add additional hook post-upgrade

### PR DESCRIPTION
**Pull request by nightguide**
**What this PR does / why we need it**: Added the ability to Installing/updating providers resources and ns's after the Helm chart has already been installed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by nightguide** [comment]
@Fedosin 
@alexander-demicev 
Hi all, plz check my PR.
Thanks.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Pull request merged**
