### PR TITLE
✨ Ability to add provider specific featureGates with Helm

### LINKED ISSUE #447: Ability to add provider specific featureGates with Helm
**User Story**

As a operator I would like to  have the ability to add provider specific featureGates. 

**Detailed Description**
Currently manager _featureGates_ are only added to the **InfrastructureProvider**.
There is no option to add _featureGates_ to **CoreProvider** (eg. MachinePool)
Adding all _featureGates_ to **CoreProvider** will often break the deployment because of provider specific _featureGates_ that are not compatible with the **CoreProvider** (eg. EKSEnableIAM ).

Example:
* Add support for provider specific featureGates
https://github.com/kubernetes-sigs/cluster-api-operator/commit/6c9e585f23e59e9da3c1a45c2e878a5b74fdc04e

* Add featureGates to CoreProvider
https://github.com/kubernetes-sigs/cluster-api-operator/commit/fa051d40f9c7cbde2aa01855567f412ecead4a8a

values.yaml:
```
manager:
  featureGates:
    core:
      ClusterTopology: true
      MachinePool: true
    aws:
      EKSEnableIAM: true
      EKSAllowAddRoles: true
      ClusterTopology: true
      MachinePool: true
```

/kind feature

### PR DESCRIPTION
**Pull request by oprinmarius**
**What this PR does / why we need it**:
Ability to add provider specific featureGates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #447 

I used the following values:
```
image:
  manager:
    tag: v0.9.0
cert-manager:
  enabled: false
  installCRDs: false
addon: helm
infrastructure: "aws:v2.4.0"
core: "cluster-api:v1.6.2"
configSecret: 
  name: aws-variables
  namespace: default
manager:
  featureGates:
    core:
      ClusterTopology: true
      MachinePool: true     
    aws:
      EKSEnableIAM: true
      EKSAllowAddRoles: true
      ClusterTopology: true
      MachinePool: true
```

### CODE REVIEW

**Comment by zioproto** [comment]
How do you test this?

I tried:

```
cd cluster-api-operator/hack/charts
helm template --set infrastructure=azure:v1.13.2   \
                         --set addon=helm --set cert-manager.enabled=false \
                         --set image.manager.tag=v0.9.0 \
                         --set manager.featureGates.core.MachinePool=true  \
                         --set manager.featureGates.azure.MachinePool=true  \
                         --set manager.featureGates.azure.ClusterTopology=true \
                         --set manager.featureGates.azure.ClusterResourceSet=true \
                         --wait capi ./cluster-api-operator
```

But the template `core.yaml` is not rendered. However I don't pass additional `--set` values when I use the chart.

**Comment by oprinmarius** [comment]
> How do you test this?
> 
> I tried:
> 
> ```
> cd cluster-api-operator/hack/charts
> helm template --set infrastructure=azure:v1.13.2   \
>                          --set addon=helm --set cert-manager.enabled=false \
>                          --set image.manager.tag=v0.9.0 \
>                          --set manager.featureGates.core.MachinePool=true  \
>                          --set manager.featureGates.azure.MachinePool=true  \
>                          --set manager.featureGates.azure.ClusterTopology=true \
>                          --set manager.featureGates.azure.ClusterResourceSet=true \
>                          --wait capi ./cluster-api-operator
> ```
> 
> But the template `core.yaml` is not rendered. However I don't pass additional `--set` values when I use the chart.

I used the following values:

```
image:
  manager:
    tag: v0.9.0
cert-manager:
  enabled: false
  installCRDs: false
addon: helm
infrastructure: "aws:v2.4.0"
core: "cluster-api:v1.6.2"
configSecret: 
  name: aws-variables
  namespace: default
manager:
  featureGates:
    core:
      ClusterTopology: true
      MachinePool: true     
    aws:
      EKSEnableIAM: true
      EKSAllowAddRoles: true
      ClusterTopology: true
      MachinePool: true
```

**Comment by oprinmarius** [comment]
@zioproto I think you need to specify core provider version for the template to be rendered:
https://github.com/kubernetes-sigs/cluster-api-operator/blob/006442ff0af5cb69a8e939f6853810918d4b7602/hack/charts/cluster-api-operator/templates/core.yaml#L2

**Comment by alexander-demicev** [comment]
Hi, thanks for working on this. We have a set of e2e tests for ensuring helm chart works as expected https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/test/e2e/helm_test.go. Can you add some tests for feature gates there?

**Comment by alexander-demicev** [comment]
@zioproto by default `helmChart.Run(...)` will only print resources that helm hooks, that's why only providers are in the output.

**Review by alexander-demicev — APPROVED** [review]
/approve

**Comment by jackfrancis** [comment]
Apologies for the blast

@Danil-Grigorev @Fedosin @alexander-demicev @damdo @furkatgofurov7 could we get an lgtm to land this fix and unblock some provider workflows that use cluster-api-operator?

Thank you!

**Review by Danil-Grigorev — COMMENTED** [review]
/approve

**Review by Danil-Grigorev — COMMENTED** [review]
/lgtm

**Pull request merged**
