### PR TITLE
🌱 udpate goreleaser config to include ldflags

### LINKED ISSUE #398: use ldflags during build
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
```bash
$ ./bin/clusterctl-operator version
CAPI operator version: &version.Info{Major:"", Minor:"", GitVersion:"", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you expect to happen:**
We should propogate ldflags correctly using goreleaser. 

I am looking into it but so far I was not able to find a way to propogate ldflags to goreleaser config using a script. I've asked for support around it. 
If I find a way to pass it, I'll create a patch for the same. 

If above doesn't work, I'll pass is manually to goreleaser config but we might have to omit some field. 
```yaml
  ldflags:
  - -s -w 
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitVersion={{.Version}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitCommit={{.Commit}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.buildDate={{.Date}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitTreeState={{ .IsGitDirty }}'
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: 0.8.1
- Cluster-api version: 1.6.1
- Minikube/KIND version: 0.20.0
- Kubernetes version: (use `kubectl version`): 1.28.1
- OS (e.g. from `/etc/os-release`): fedora

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by kranurag7**
**What this PR does / why we need it**:
- for version subcommand. 
- validated using `goreleaser release --snapshot` 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #398

### CODE REVIEW

**Review by Fedosin — COMMENTED** [review]
Hey! thank you for this change!
I think the goreleaser part is good, but could you restore the script, because it is used in our [Makefile](https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/Makefile#L140)

**Comment by kranurag7** [comment]
Thanks Mike, I restored it (`git checkout HEAD^ hack/version.sh`) and force pushed.

**Review by Fedosin — APPROVED** [review]
/approve

**Review by Danil-Grigorev — COMMENTED** [review]
/lgtm

**Pull request merged**
