### PR TITLE
🌱 Bump go version to v1.21

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:

CAPI uses golang v1.21: https://github.com/kubernetes-sigs/cluster-api/pull/9900. We need to do the same.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@Fedosin 👋🏼, CAPI v1.6.X does not use go 1.21 AFAICT https://github.com/kubernetes-sigs/cluster-api/blob/v1.6.0/.golangci.yml#L3, the PR you linked merged into 1.7 milestone

**Comment by Fedosin** [comment]
@furkatgofurov7 right, in v1.6 they are still on golang v1.20. there is no need to merge this pr right now

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
