### PR TITLE
🌱 Disable dependabot for hack/* modules

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:
It's not necessary to update dependency for internal tools so frequently. So, it's better to disable dependabot for them, or otherwise it creates to many PRs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
>It's not necessary to update dependency for internal tools so frequently. So, it's better to disable dependabot for them, or otherwise it creates to many PRs.


If it is just too frequent but we still need updates, we could increase the interval of updates done by the bot and keep it running, otherwise, let's remove it completely

**Comment by alexander-demicev** [comment]
can we do monthly updates? For test package also maybe

**Review by furkatgofurov7 — APPROVED** [review]

**Review by alexander-demicev — APPROVED** [review]
/lgtm

**Pull request merged**
