### PR TITLE
📖Document setting up new release branch jobs in release.md

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Documents all the steps to create new release branch jobs after we branch out to new release branch in the repo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to: https://github.com/kubernetes/test-infra/pull/30372

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/hold

until https://github.com/kubernetes/test-infra/pull/30372 is merged

**Comment by furkatgofurov7** [comment]
/hold cancel

infra PR is merged now

**Review by Danil-Grigorev — APPROVED** [review]

**Pull request merged**
