### PR TITLE
🌱 Bump cluster-api to v1.7.0

### LINKED ISSUE #464: Can't install an infrastructure provider if the github tag for a release exists but the release doesn't.
**What steps did you take and what happened:**

At time of writing, CAPA v2.4.1 has an extant tag, but not an extant release.  According to the folks over at CAPA, this is normal for them, and it usually takes about half an hour from tag creation to release creation.

Screenshot 2024-03-18 at 10 35 29 AM
Screenshot 2024-03-18 at 10 35 36 AM

I attempted to install the AWS provider in my cluster (in an integration test, using a config which has worked before).  To emphasize - I am _not_ attempting to use the new, incomplete release, I am attempting to use the previous release.

Unfortunately, the provider was not installed, and here are the relevant portions of the logs:

```
I0318 17:36:12.526031       1 preflight_checks.go:57]  "msg"="Performing preflight checks" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
I0318 17:36:12.536389       1 preflight_checks.go:206]  "msg"="Preflight checks passed" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
I0318 17:36:12.990526       1 manifests_downloader.go:77]  "msg"="Downloading provider manifests" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
E0318 17:37:13.260243       1 controller.go:329]  "msg"="Reconciler error" "error"="failed to create repo from provider url for provider \"aws\": error creating the GitHub repository client: failed to get latest release: release not found for version v2.4.1, please retry later or set \"GOPROXY=off\" to get the current stable release: 404 Not Found" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
```

**What did you expect to happen:**

I expected the provider to be installed despite CAPA's in-progress release.

**Environment:**

- Cluster-api-operator version: 0.8.1
- Cluster-api version: 1.6.2
- Kubernetes version: (use `kubectl version`): 1.27.3

/kind bug

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:

This PR bumps Cluster API libraries to v1.7.0. This updates includes an important bug fix: https://github.com/kubernetes-sigs/cluster-api/pull/10220

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #464

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
LGTM, only one question:

We have core capi [manifests](https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/test/e2e/resources) (v1.5.4/v1.6.0) for airgapped e2e tests, are we planning to update those in general (as follow-up) or in the same PR?

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by Fedosin** [comment]
> LGTM, only one question:
> 
> We have core capi [manifests](https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/test/e2e/resources) (v1.5.4/v1.6.0) for airgapped e2e tests, are we planning to update those in general (as follow-up) or in the same PR?

I don't think we have plans to update them now... Using older versions is okay imo.

**Review by alexander-demicev — APPROVED** [review]
/approve

**Pull request merged**
