### PR TITLE
🐛 Restrict configmap lookup to the provider namespace

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:

When we use configmaps as a provider source, we filter them by provided labels and then take the latest version. Unfortunately, we list configmaps in all namespaces, which is not correct.

This PR restricts the search by the provider namespace only.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by Danil-Grigorev — COMMENTED** [review]
/lgtm
Thank you

**Review by alexander-demicev — APPROVED** [review]
/approve

**Pull request merged**
