### PR TITLE
📖 Inital Netlify book structure version of operator

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

This commit puts together the skeleton of Netlify book structure and
by no means a final one and subject to change and iterations. Builds on top of https://github.com/kubernetes-sigs/cluster-api-operator/pull/433 and will be rebased once it is merged.

To try it, run from `docs/book` folder:

1.  `make build`
2. `make serve`
3. navigate to `http://localhost:3000` to see the local version of the book deployed

Screenshot 2024-02-26 at 11 30 27

Related to: #329

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
#423 is merged and rebased this PR on top of it now, next waiting for Netlify site and DNS issues to be resolved before we take this in. 

/hold

**Comment by furkatgofurov7** [comment]
/hold cancel

Netlify site and DNS records are all setup: https://cluster-api-operator.sigs.k8s.io/

so, this is ready for review. 

/cc @Fedosin @alexander-demicev

**Review by Fedosin — APPROVED** [review]
you rock!

/approve

**Comment by Danil-Grigorev** [comment]
@furkatgofurov7 Can you please follow previous naming convention from initial book structure? This way it does not need to update SUMMARY.md, it is done automatically.

**Review by Fedosin — APPROVED** [review]
/lgtm

**Pull request merged**
