### PR TITLE
🌱 Bump CAPI to v1.6.0

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Bumps Cluster API to 1.6.0 minor release https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Fedosin** [comment]
https://github.com/kubernetes-sigs/cluster-api-operator/pull/358

**Comment by furkatgofurov7** [comment]
@alexander-demicev @Fedosin can we take this in?

**Review by Fedosin — APPROVED** [review]
/approve

**Pull request merged**
