### PR TITLE
🌱 Update owners

### PR DESCRIPTION
**Pull request by Fedosin**
**What this PR does / why we need it**:

Add [Danil-Grigorev](https://github.com/Danil-Grigorev) to admins and maintainers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks @Danil-Grigorev for all the contributions so far, welcome!

/lgtm

**Review by alexander-demicev — APPROVED** [review]
/lgtm

**Review by Fedosin — COMMENTED** [review]
/approve

**Pull request merged**
